name: CI (api)

on:
  push:
    branches: main
    paths:
      - api
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: api

      - uses: actions/setup-python@v5
        with:
          cache: 'pip'

      - name: Install dependencies
        run: |
          cd api
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          cd api
          pytest

