name: CI (web)

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    shell: bash

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

